### ISSUE TITLE
super minor documentation issue

### ISSUE THREAD

**Issue by PeterQuinn925** [chaunceygardiner/weewx-nws#1]
Hi, looks like a nice extension. I've installed it on my test site .  

Noticed what I think is a typo in the readme.

It says under [Configuring-Weewx-NWS](https://github.com/chaunceygardiner/weewx-nws#configuring-weewx-nws)
` User-Agent: '(my-weather-site.com, me@my-weather-site.com)'`

I think it should be
` User-Agent = '(my-weather-site.com, me@my-weather-site.com)'`

**Comment by chaunceygardiner** [comment]
Thanks.  Fixed at [59bf69b](https://github.com/chaunceygardiner/weewx-nws/commit/8a61a12ef4cb53c5b252ea04698f0f53f853ee8a).
