### ISSUE TITLE
How to tell what location the forecast is using

### ISSUE THREAD

**Issue by PeterQuinn925** [chaunceygardiner/weewx-nws#2]
I'm getting odd forecast results. The temps have often been a few degrees low. The forecast I'm seeing is calling for a chance of snow tonight. We haven't had snow here since 1986, so it's kind of doubtful. How can I tell that it's pulling the right location?

I double checked the NWS site manually and has a sensible forecast for my zip code.

I just added lat/long to the NWS section of weewx.conf to see if that helps. It doesn't appear to have generated a new forecast yet, so maybe that will fix it.

**Comment by chaunceygardiner** [comment]
You did not need to add the lat/long to the NWS section.

You can take same steps (that the plugin performs) in your browser.
Navigate to https://api.weather.gov/points/<latitude>,<longitude>
Use the latitude and longitude you have set in weewx.conf.
For example:
My lat long is:
[Station]                                                                                                                                                                 
                                                                                                                                                                          
    # Description of the station location                                                                                                                                 
    location = "Palo Alto, CA"                                                                                                                                            
                                                                                                                                                                          
    # Latitude and longitude in decimal degrees                                                                                                                           
    latitude = 37.431495
    longitude = -122.110937

So for me, the url is:
https://api.weather.gov/points/37.431495,-122.110937

In the page returned, you will see the 12-hour and 1-hour forecasts.  For the above, it’s:
        "forecast": "https://api.weather.gov/gridpoints/MTR/91,87/forecast",
        "forecastHourly": "https://api.weather.gov/gridpoints/MTR/91,87/forecast/hourly",

Navigate to the two URLs for 12 and 1 hour forecasts.  If you have complaints about the forecast, NWS would be where to direct those complaints.

If you are in the SF Bay Area, some parts are/were showing a small chance of snow.

**Comment by chaunceygardiner** [comment]
I forgot to add:
The URLs I mentioned above will also be in the log.  Have a look to verify your lat/long is being used, etc.

**Comment by chaunceygardiner** [comment]
Hi Peter,

There is a chance that NWS could have changed the URLs for getting the point forecast since the start of WeeWX.  To guard against such a possibility, I just published v1.3.  This version re-fetches the URLs every time before fetching forecasts.

Cheers,
John
