### ISSUE TITLE
Errors on Versions above 1.5

### ISSUE THREAD

**Issue by dshanske** [chaunceygardiner/weewx-nws#3]
Feb 12 00:37:48 backend python3[22095]: weewx[22095] CRITICAL __main__: Caught unrecoverable exception:
Feb 12 00:37:48 backend python3[22095]: weewx[22095] CRITICAL __main__:     ****  Unknown boolean specifier: 'None'.
Feb 12 00:37:48 backend python3[22095]: weewx[22095] CRITICAL __main__:     ****  Traceback (most recent call last):
Feb 12 00:37:48 backend python3[22095]: weewx[22095] CRITICAL __main__:     ****    File "/usr/share/weewx/weewxd", line 147, in main
Feb 12 00:37:48 backend python3[22095]: weewx[22095] CRITICAL __main__:     ****      engine = weewx.engine.StdEngine(config_dict)
Feb 12 00:37:48 backend python3[22095]: weewx[22095] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 93, in __init__
Feb 12 00:37:48 backend python3[22095]: weewx[22095] CRITICAL __main__:     ****      self.loadServices(config_dict)
Feb 12 00:37:48 backend python3[22095]: weewx[22095] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 161, in loadServices
Feb 12 00:37:48 backend python3[22095]: weewx[22095] CRITICAL __main__:     ****      obj = weeutil.weeutil.get_object(svc)(self, config_dict)
Feb 12 00:37:48 backend python3[22095]: weewx[22095] CRITICAL __main__:     ****    File "/usr/share/weewx/user/nws.py", line 214, in __init__
Feb 12 00:37:48 backend python3[22095]: weewx[22095] CRITICAL __main__:     ****      enable                         = to_bool(rsync_spec_dict.get('enable')),
Feb 12 00:37:48 backend python3[22095]: weewx[22095] CRITICAL __main__:     ****    File "/usr/share/weewx/weeutil/weeutil.py", line 1307, in tobool
Feb 12 00:37:48 backend python3[22095]: weewx[22095] CRITICAL __main__:     ****      raise ValueError("Unknown boolean specifier: '%s'." % x)
Feb 12 00:37:48 backend python3[22095]: weewx[22095] CRITICAL __main__:     ****  ValueError: Unknown boolean specifier: 'None'.
Feb 12 00:37:48 backend python3[22095]: weewx[22095] CRITICAL __main__:     ****  Exiting.

Any advice on this?

**Comment by chaunceygardiner** [comment]
Yes, until I fix this, add the following at the end of the [NWS] section in weewx.conf

    [[RsyncSpec]]                                                                                                      
        enable = false

**Comment by chaunceygardiner** [comment]
Oops, there are other booleans I have to fix.  I’ll have a new version shortly.  Hang on.

**Comment by chaunceygardiner** [comment]
I just published v1.9 to fix this.  Please give it a try.

**Comment by chaunceygardiner** [comment]
Please reopen if you still have an issue.
