### ISSUE TITLE
check_grid.py requires install of matplotlib

### ISSUE THREAD

**Issue by PeterQuinn925** [chaunceygardiner/weewx-nws#4]
This is a documentation issue, really. When I tried to run check_grid.py, I didn't already have matplotlib installed, so it failed to run. 
Doing 
sudo apt install python3-matplotlib

and then running it again fixed the problem.

(I tried pip install matplotlib but it appears to freeze while installing. Googling, it seems like it's probably trying to compile it and taking a very very long time.)

You might mention that you need to install matplotlib prior to running check_grid but you don't need it to run the extension otherwise

**Comment by chaunceygardiner** [comment]
Thanks for filing this.  I updated the README to reflect this requirement.
