### ISSUE TITLE
Missing math import statement in alerts.html.tmpl

### ISSUE THREAD

**Issue by N1OTX** [chaunceygardiner/weewx-nws#8]
Installed latest on 04//17/2004
Service version is 4.3.
Sample Report fails with weewx.cheetahgenerator
Jul 17 12:45:32 cont-weewx-testing weewxd[108714]: ERROR weewx.cheetahgenerator: Evaluation of template /home/panders/weewx-data/skins/nws/alerts.html.tmpl failed with exception '<class 'NameError'>'
Jul 17 12:45:32 cont-weewx-testing weewxd[108714]: ERROR weewx.cheetahgenerator: **** Ignoring template /home/panders/weewx-data/skins/nws/alerts.html.tmpl
Jul 17 12:45:32 cont-weewx-testing weewxd[108714]: ERROR weewx.cheetahgenerator: **** Reason: name 'math' is not defined
Jul 17 12:45:32 cont-weewx-testing weewxd[108714]: ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Jul 17 12:45:32 cont-weewx-testing weewxd[108714]: ERROR weewx.cheetahgenerator: ****    File "/home/panders/weewx-venv/lib/python3.11/site-packages/weewx/cheetahgenerator.py", line 334, in generate
Jul 17 12:45:32 cont-weewx-testing weewxd[108714]: ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
Jul 17 12:45:32 cont-weewx-testing weewxd[108714]: ERROR weewx.cheetahgenerator: ****                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 17 12:45:32 cont-weewx-testing weewxd[108714]: ERROR weewx.cheetahgenerator: ****    File "_home_panders_weewx_data_skins_nws_alerts_html_tmpl.py", line 321, in respond
Jul 17 12:45:32 cont-weewx-testing weewxd[108714]: ERROR weewx.cheetahgenerator: ****  NameError: name 'math' is not defined

Appears /skins/nws/alerts.html.tmpl is missing a math import statement. Adding that, and nothing else,seems to fix the issue.

Paul

**Comment by chaunceygardiner** [comment]
Thanks for reporting this.  Fixed in just now released v4.4.
